spring:
  application:
    name: duhacksbackend
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Mr.VivekThumar@2004
    url: jdbc:postgresql://localhost:5432/duhacks
  liquibase:
    enabled: false
    change-log: classpath:/db/changelog/db.changelog-master.xml
    default-schema: public
    contexts: development
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: darkdark2189@gmail.com
    password: ppofakoutvdyrffg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: VGhpcy1pczEtU3VwZXItU2VjcmV0LUtleS1Gb3ItSldU


server:
  port: 8888